const API = window.ARKAN_API || '/api';
const $ = (selector) => document.querySelector(selector);
const notice = $('#notice');
const escapeHtml = (value) => String(value ?? '').replace(/[&<>'"]/g, (char) => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
function showNotice(message, error = false) { notice.textContent = message; notice.className = `notice ${error ? 'error' : 'success'}`; notice.hidden = false; setTimeout(() => { notice.hidden = true; }, 4000); }
async function request(path, options = {}) { const response = await fetch(`${API}${path}`, options); if (!response.ok) { const body = await response.json().catch(() => ({})); throw new Error(body.detail || `Request failed (${response.status})`); } return response.status === 204 ? null : response.json(); }
function status(value) { return `<span class="status ${escapeHtml(value)}">${escapeHtml(value)}</span>`; }
function jobsTable(jobs) { if (!jobs.length) return '<p class="muted">No jobs yet.</p>'; return `<table><thead><tr><th>Job</th><th>Tool</th><th>Status</th><th>Updated</th><th></th></tr></thead><tbody>${jobs.map((job) => `<tr><td class="mono">${escapeHtml(job.id.slice(0, 8))}</td><td>${escapeHtml(job.engine)}</td><td>${status(job.status)}</td><td>${escapeHtml(job.updated_at || job.created_at || '')}</td><td><button class="link job-result" data-job-id="${escapeHtml(job.id)}">View</button></td></tr>`).join('')}</tbody></table>`; }
function navigate(view) { document.querySelectorAll('.view').forEach((element) => { element.hidden = element.id !== view; }); document.querySelectorAll('.nav').forEach((element) => element.classList.toggle('active', element.dataset.view === view)); if (view === 'projects') loadProjects(); if (view === 'jobs') loadJobs(); if (view === 'engines') loadEngines(); }
document.querySelectorAll('[data-view], [data-view-target]').forEach((element) => element.addEventListener('click', () => navigate(element.dataset.view || element.dataset.viewTarget)));
async function loadOverview() { try { const [projects, jobs, engines] = await Promise.all([request('/projects'), request('/jobs'), request('/engines')]); $('#project-count').textContent = projects.projects.length; $('#job-count').textContent = jobs.jobs.length; $('#engine-count').textContent = engines.engines.length; $('#recent-jobs').innerHTML = jobsTable(jobs.jobs.slice(0, 5)); bindResultButtons(); await populateProjectForms(projects.projects, engines.engines); } catch (error) { showNotice(error.message, true); } }
async function populateProjectForms(projects, engines) { const projectOptions = '<option value="">Select project</option>' + projects.map((p) => `<option value="${escapeHtml(p.id)}">${escapeHtml(p.name)}</option>`).join(''); $('#artifact-project').innerHTML = projectOptions; $('#job-project').innerHTML = projectOptions; $('#job-engine').innerHTML = '<option value="">Select tool</option>' + engines.map((e) => `<option value="${escapeHtml(e.name)}">${escapeHtml(e.name)}</option>`).join(''); await loadArtifacts($('#job-project').value); }
async function loadArtifacts(projectId) { if (!projectId) { $('#job-artifact').innerHTML = '<option value="">Select artifact</option>'; return; } const data = await request(`/projects/${encodeURIComponent(projectId)}/artifacts`); $('#job-artifact').innerHTML = '<option value="">Select artifact</option>' + data.artifacts.map((a) => `<option value="${escapeHtml(a.id)}">${escapeHtml(a.name)} · ${escapeHtml(a.language)}</option>`).join(''); }
async function loadProjects() { try { const data = await request('/projects'); $('#projects-list').innerHTML = data.projects.length ? data.projects.map((project) => `<article class="project card"><h3>${escapeHtml(project.name)}</h3><p class="muted">${escapeHtml(project.description || 'No description')}</p><span class="mono">${escapeHtml(project.id)}</span></article>`).join('') : '<p class="muted">Create your first project.</p>'; const engines = await request('/engines'); await populateProjectForms(data.projects, engines.engines); } catch (error) { showNotice(error.message, true); } }
async function loadJobs() { try { const data = await request('/jobs'); $('#jobs-list').innerHTML = jobsTable(data.jobs); bindResultButtons(); } catch (error) { showNotice(error.message, true); } }
async function loadEngines() { try { const data = await request('/engines'); $('#engines-list').innerHTML = data.engines.map((engine) => `<article class="engine card"><div class="engine-header"><h3>${escapeHtml(engine.name)}</h3>${status('available')}</div><p class="muted">${escapeHtml(engine.description || '')}</p><small>${escapeHtml((engine.languages || []).join(', '))}</small></article>`).join(''); } catch (error) { showNotice(error.message, true); } }
async function showResult(id) { try { const job = await request(`/jobs/${encodeURIComponent(id)}`); $('#job-result').hidden = false; $('#result-content').textContent = JSON.stringify(job.result || {status: job.status, error: job.error}, null, 2); navigate('jobs'); } catch (error) { showNotice(error.message, true); } }
function bindResultButtons() { document.querySelectorAll('.job-result').forEach((button) => button.addEventListener('click', () => showResult(button.dataset.jobId))); }
$('#job-project').addEventListener('change', (event) => loadArtifacts(event.target.value).catch((error) => showNotice(error.message, true)));
$('#project-form').addEventListener('submit', async (event) => { event.preventDefault(); try { await request('/projects', {method: 'POST', headers: {'Content-Type': 'application/json'}, body: JSON.stringify({name: $('#project-name').value, description: $('#project-description').value || null})}); event.target.reset(); showNotice('Project created'); await loadProjects(); await loadOverview(); } catch (error) { showNotice(error.message, true); } });
$('#artifact-form').addEventListener('submit', async (event) => { event.preventDefault(); const project = $('#artifact-project').value; const file = $('#artifact-file').files[0]; if (!project || !file) return showNotice('Select a project and file', true); const form = new FormData(); form.append('language', $('#artifact-language').value); form.append('file', file); try { await request(`/projects/${encodeURIComponent(project)}/artifacts/upload?language=${encodeURIComponent($('#artifact-language').value)}`, {method: 'POST', body: form}); event.target.reset(); showNotice('Artifact uploaded'); await loadProjects(); } catch (error) { showNotice(error.message, true); } });
$('#job-form').addEventListener('submit', async (event) => { event.preventDefault(); try { const job = await request('/jobs', {method: 'POST', headers: {'Content-Type': 'application/json'}, body: JSON.stringify({project_id: $('#job-project').value, artifact_id: $('#job-artifact').value, engine: $('#job-engine').value})}); showNotice(`Job queued: ${job.id.slice(0, 8)}`); await loadJobs(); await loadOverview(); } catch (error) { showNotice(error.message, true); } });
loadOverview();
